name: CI - EntryTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  pull-source-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

